name: Alexander El-Hajj
description: Making everything more efficient should make everybody happier. - Geoffrey Hinton
url: https://a-elhajj.github.io
lang: en
google_analytics_id: "G-T40TCT7J8D"
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .cursor
