name: Alexander El-Hajj
description: Making everything more efficient should make everybody happier. - Geoffrey Hinton
url: https://a-elhajj.github.io
lang: en
google_analytics_id: ""
markdown: kramdown
